node {

stage('Cloning source code')
{
    checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/snehalgaikwad12/FinalCalci.git/']]])
}
stage('Static Code Analysis')
{
      
        withSonarQubeEnv('SonarScanner') {
            sh 'mvn clean package sonar:sonar'
            sh 'mvn sonar:sonar \
  -Dsonar.projectKey=login \
  -Dsonar.host.url=http://35.244.5.144:9000 \
  -Dsonar.login=c88ea683811312b597251330f87f14d8acfc946c'
        }
}
stage("Quality Gate") 
{
       timeout(time: 1, unit: 'MINUTES') 
       {
            def qg = waitForQualityGate()
            if (qg.status != 'OK') {
                  error "Pipeline aborted due to quality gate failure: ${qg.status}"
                 }

       }
}
stage('Build and Test')
{
     sh 'mvn clean package'
}
stage('publish to Nexus')
{
   sh 'curl -v -u admin:admin123 --upload-file /bitnami/jenkins/jenkins_home/workspace/Calci/target/Calculator_dev.war http://35.243.131.61:8081/nexus/content/repositories/calci/'
  
   
}
stage('deploy')
{ 
    sh 'curl --upload-file /bitnami/jenkins/jenkins_home/workspace/Calci/target/Calculator_dev.war "http://tomcat:tomcat@35.243.131.61:8090/manager/text/deploy?path=/calci&update=true"'
}
 
}
